#!/usr/bin/env bash
# It installs nginx on your web-01
# It should print Hello Worls!

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
