#!/usr/bin/env bash
# Update the package list and install Nginx
# Allow HTTP traffic through UFW
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

# Create index.html and 404.html files
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx server block
sudo tee /etc/nginx/sites-enabled/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }

    if (\$request_filename ~ redirect_me){
        rewrite ^ https://youtube.com permanent;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL

# Restart Nginx to apply changes
sudo service nginx restart

