#!/usr/bin/env bash
# It is IP address received as argument 5 times

# It checks if there is at least one argument provided
if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  # Use 'ping' - send 5 ICMP echo requests - IP address.
  # It is basic network connectivity test.
  ping -c 5 "$1"
fi
