#!/usr/bin/env bash
# Nums from 1-20 in addition to:
#   "bad luck from China" 4th iter
#   "bad luck from Japan" 9th iter
#   "bad luck from Italy" 17th loop iter

x=1

while [ $x -le 20 ]
do
  echo "$x"
  case $x in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( x++ ))
done
